version: '1.0.{build}'
configuration:
- Debug
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\SeamsCore" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- pwd
- ls
test_script:
- dotnet test "test\SeamsCore.UnitTests" -c %CONFIGURATION%
artifacts:
- path: src\SeamsCore\dist\
  name: web-app
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://seamscore.scm.azurewebsites.net:443/msdeploy.axd?site=seamscore
  website: seamscore
  username: $seamscore
  password:
    secure: i4QRKs57wCtkFV2nSvkXP2mDhfvWkWrW7irg9H2c3EmHIpYSW0X++1mqcax5XzpyyAGHjBeLYpjN5+HHdm79qA==
  artifact: web-app
  remove_files: true
  aspnet_core: true
  aspnet_core_force_restart: true 